### ISSUE TITLE
Unsubscibe from emails should be built into site, not open the Listserv email command

### ISSUE THREAD

**Issue by david-shortman** [UA-ACM-Student-Chapter/UA-ACM-Student-Chapter.github.io#10]
The unsubscribe from list link in the footer of the site (and emails) should work like normal unsubscribe links. It's currently a mailto link with a Listserv command.

Clicking unsubscribe should prompt "Are you sure?" and then yes or no.

**Comment by mayank99** [comment]
Wait, why was this closed? It never materialized.

**Comment by david-shortman** [comment]
I raised this issue two years ago. If you think it will be addressed feel free to re-open it.
