### ISSUE TITLE
Bruh this thing is messed up

### ISSUE THREAD

**Issue by david-mccoy** [UA-ACM-Student-Chapter/UA-ACM-Student-Chapter.github.io#33]
![Screenshot 2019-09-14 11 04 05](https://user-images.githubusercontent.com/25187726/64909893-79bd2200-d6df-11e9-9fa7-5e52a8ab4ad8.png)

**Comment by jdogwilly** [comment]
So fix it 🤷🏼‍♂️

**Comment by mayank99** [comment]
Tea

**Comment by mayank99** [comment]
+ @elmines @hjbugajski

**Comment by mayank99** [comment]
#34
